cd DEALER/unikernel
mirage clean
cd ../../DEALER/unikernel_bind
mirage clean
cd ../../IDENTITY/unikernel
mirage clean
cd ../../PAIR/unikernel1
mirage clean
cd ../../PAIR/unikernel2
mirage clean
cd ../../PLAIN/client_unikernel
mirage clean
cd ../../PLAIN/server_unikernel
mirage clean
cd ../../PUB/unikernel
mirage clean
cd ../../PULL/unikernel
mirage clean
cd ../../PUSH/unikernel
mirage clean
cd ../../Queue_size/PUSH_send_limited
mirage clean
cd ../../Queue_size/SUB_receive_limited
mirage clean
cd ../../REP/unikernel
mirage clean
cd ../../REQ/unikernel
mirage clean
cd ../../ROUTER/unikernel
mirage clean
cd ../../ROUTER/unikernel_connect
mirage clean
cd ../../SUB/unikernel
mirage clean
cd ../../XPUB/unikernel
mirage clean
cd ../../XSUB/unikernel
mirage clean